version: '3.4'

services:
  netcorewithdocker:
    image: netcorewithdocker
    ports:
      - 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/netcorewithdocker.pfx
    volumes:
      - ~/.aspnet/https:/https:ro