version: '3.4'

services:
  netcorewithdocker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password@123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/aspnet/https/netcorewithdocker.pfx
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${USERPROFILE}/.aspnet/Https:/root/.aspnet/https:ro